name: LighthouseCI

on: [push]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: install, build
        run: |
          pnpm i
          pnpm build
      - name: run Lighthouse CI
        run: |
          pnpm install -g @lhci/cli@0.14.x
          lhci autorun
